# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6a5bab7e3ee600b9ffd8ef22ad25ff8cde0072cc0d25f1196759e23db84beb439402f7c7d9c6ac330eb0cde7529863a7daf3c14ee7a33bf3c7f8d13b30c42e7

test:
  secret_key_base: ddfb82891cd8e4247193d6d57e681ea1bbd5bed85346d6f86979c0344bd5277c41324daed8b1c97f0975996bcf1520735e7ac15ea55d50a3444dd3ba02469cd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
